server:
  port: 8080

spring:
  jackson:
    serialization:
      indent-output: true

  datasource:
    url: jdbc:mysql://localhost:3306/wheats?serverTimezone=Asia/Seoul&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: wheats
    password: wheats
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none        # 테이블은 schema.sql에서 생성하니까 여기서는 건들지 않도록 none
    show-sql: true          # 콘솔에 SQL 찍기
    properties:
      hibernate:
        format_sql: true    # SQL 이쁘게 출력

# OAuth 서버 설정
oauth:
  server:
    url: http://localhost:3000  # 로컬 개발 시에는 localhost 사용

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 매핑된 엔드포인트 확인용
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: INFO
    com.wheats.api.auth: DEBUG